# JDBC Configuration
jdbc.url=jdbc:mysql://localhost:3306/grocerify
jdbc.username=root
jdbc.password=IronMan16

# Solace Configuration
solace.url=mr-connection-1i2ikarlnua.messaging.solace.cloud:55555  
solace.vpn=puri
solace.username=solace-cloud-client
solace.password=wrong
